log_level                :info
log_location             STDOUT
node_name                'admin'
client_key               '/home/devopsadmin/.chef/admin.pem'
validation_client_name   'chef-validator'
#validation_key           '/etc/chef-server/chef-validator.pem'
validation_key           '/home/devopsadmin/devops/Assignment/chef-repo/.chef/chef-validator.pem'
chef_server_url          'https://delvmplmMEDTR04.sapient.com:443'
syntax_check_cache_path  '/home/devopsadmin/.chef/syntax_check_cache'
cookbook_path            '/home/devopsadmin/devops/Assignment/chef-repo/cookbooks/'
